# Generated by Django 4.2.29 on 2026-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_goal_goalcontribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="monthly_budget",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
