# Generated by Django 4.2.29 on 2026-03-14 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_user_monthly_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="auto_categorized",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MerchantRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normalized_name", models.CharField(max_length=500)),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_rules",
                        to="core.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "normalized_name")},
            },
        ),
    ]
