# Generated by Django 4.2.29 on 2026-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_transaction_auto_categorized_merchantrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[("expense", "Expense"), ("income", "Income")],
                default="expense",
                max_length=7,
            ),
        ),
    ]
