# Generated by Django 4.2.29 on 2026-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_add_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("chequing", "Chequing"),
                    ("savings", "Savings"),
                    ("credit_card", "Credit Card"),
                ],
                default="chequing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="credit_limit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
