# Generated by Django 4.2.29 on 2026-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_delete_csvupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="goal_type",
            field=models.CharField(
                choices=[("savings", "Savings"), ("spending", "Spending"), ("debt", "Debt")],
                max_length=10,
            ),
        ),
    ]
